// Date: 27.04.2015 19:30:25
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX



package com.bparcuctembi.schoolmod;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class KarimMobModel extends ModelBase
{
  //fields
    ModelRenderer Leg1;
    ModelRenderer Leg2;
    ModelRenderer Body;
    ModelRenderer Arm1;
    ModelRenderer Arm2;
    ModelRenderer Head;
  
  public KarimMobModel()
  {
    textureWidth = 64;
    textureHeight = 128;
    
      Leg1 = new ModelRenderer(this, 0, 27);
      Leg1.addBox(-2F, 0F, -2F, 4, 25, 4);
      Leg1.setRotationPoint(-2F, -1F, 0F);
      Leg1.setTextureSize(64, 128);
      Leg1.mirror = true;
      setRotation(Leg1, 0F, 0F, 0F);
      Leg2 = new ModelRenderer(this, 0, 56);
      Leg2.addBox(-2F, 0F, -2F, 4, 25, 4);
      Leg2.setRotationPoint(3F, -1F, 0F);
      Leg2.setTextureSize(64, 128);
      Leg2.mirror = true;
      setRotation(Leg2, 0F, 0F, 0F);
      Body = new ModelRenderer(this, 24, 66);
      Body.addBox(-5F, 0F, -5F, 11, 9, 9);
      Body.setRotationPoint(0F, -5F, 0F);
      Body.setTextureSize(64, 128);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Arm1 = new ModelRenderer(this, 30, 85);
      Arm1.addBox(0F, -1F, -10F, 3, 3, 12);
      Arm1.setRotationPoint(6F, -2F, -5F);
      Arm1.setTextureSize(64, 128);
      Arm1.mirror = true;
      setRotation(Arm1, 0F, 0F, 0F);
      Arm2 = new ModelRenderer(this, 0, 85);
      Arm2.addBox(-3F, -1F, -10F, 3, 3, 12);
      Arm2.setRotationPoint(-5F, -2F, -5F);
      Arm2.setTextureSize(64, 128);
      Arm2.mirror = true;
      setRotation(Arm2, 0F, 0F, 0F);
      Head = new ModelRenderer(this, 0, 100);
      Head.addBox(-7F, -14F, -7F, 14, 14, 14);
      Head.setRotationPoint(0F, -5F, -4F);
      Head.setTextureSize(64, 128);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Leg1.render(f5);
    Leg2.render(f5);
    Body.render(f5);
    Arm1.render(f5);
    Arm2.render(f5);
    Head.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
